name: cr_cashiering_app
description: "A Flutter app for managing cashier collections and income tracking."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # Ensure the version constraint fits the SDK you're targeting

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.13.1  # Add this line

# Flutter Launcher Icons configuration
flutter_icons:  # Move this section to the root level
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # Default icon
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"  # Foreground for adaptive icon
  adaptive_icon_background: "assets/icon/icon_background.png"  # Background for adaptive icon

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/icon.png  # Default icon
    - assets/icon/icon_foreground.png  # Foreground for adaptive icon
    - assets/icon/icon_background.png  # Background for adaptive icon
